/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajos;

/**
 *
 * @author alanfor
 */
public class Ej1 extends javax.swing.JFrame {

    /**
     * Creates new form Ej1
     */
    public Ej1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbtn_suma = new javax.swing.JRadioButton();
        rbtn_resta = new javax.swing.JRadioButton();
        rbtn_multiplicacion = new javax.swing.JRadioButton();
        rbtn_division = new javax.swing.JRadioButton();
        tfld_1 = new javax.swing.JTextField();
        tfld_2 = new javax.swing.JTextField();
        lbl_resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rbtn_suma);
        rbtn_suma.setText("Suma");
        rbtn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_sumaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_resta);
        rbtn_resta.setText("Resta");
        rbtn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_restaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_multiplicacion);
        rbtn_multiplicacion.setText("Multiplicacion");
        rbtn_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_multiplicacionActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_division);
        rbtn_division.setText("Division");
        rbtn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_divisionActionPerformed(evt);
            }
        });

        tfld_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfld_1ActionPerformed(evt);
            }
        });

        lbl_resultado.setText("Resultado");
        lbl_resultado.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbtn_suma)
                        .addComponent(rbtn_resta)
                        .addComponent(rbtn_multiplicacion)
                        .addComponent(rbtn_division)
                        .addComponent(tfld_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(tfld_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfld_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfld_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rbtn_suma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn_resta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn_multiplicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn_division)
                .addGap(18, 18, 18)
                .addComponent(lbl_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Resultado");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfld_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfld_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfld_1ActionPerformed

    private void rbtn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_sumaActionPerformed
        // TODO add your handling code here
        int n1 = Integer.parseInt(tfld_1.getText());
        int n2 = Integer.parseInt(tfld_2.getText());
        int resultado = n1 + n2;
        
        lbl_resultado.setText(" " + resultado);
    }//GEN-LAST:event_rbtn_sumaActionPerformed

    private void rbtn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_restaActionPerformed
        // TODO add your handling code here:
                int n1 = Integer.parseInt(tfld_1.getText());
        int n2 = Integer.parseInt(tfld_2.getText());
        int resultado = n1 - n2;
        
        lbl_resultado.setText(" " + resultado);
    }//GEN-LAST:event_rbtn_restaActionPerformed

    private void rbtn_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_multiplicacionActionPerformed
        // TODO add your handling code here:
                        int n1 = Integer.parseInt(tfld_1.getText());
        int n2 = Integer.parseInt(tfld_2.getText());
        int resultado = n1 * n2;
        
        lbl_resultado.setText(" " + resultado);
    }//GEN-LAST:event_rbtn_multiplicacionActionPerformed

    private void rbtn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_divisionActionPerformed
        // TODO add your handling code here:
                        int n1 = Integer.parseInt(tfld_1.getText());
        int n2 = Integer.parseInt(tfld_2.getText());
        int resultado = n1 / n2;
        
        lbl_resultado.setText(" " + resultado);
    }//GEN-LAST:event_rbtn_divisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JRadioButton rbtn_division;
    private javax.swing.JRadioButton rbtn_multiplicacion;
    private javax.swing.JRadioButton rbtn_resta;
    private javax.swing.JRadioButton rbtn_suma;
    private javax.swing.JTextField tfld_1;
    private javax.swing.JTextField tfld_2;
    // End of variables declaration//GEN-END:variables
}
