/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajos;

/**
 *
 * @author alanfor
 */
public class Ej3 extends javax.swing.JFrame {
    int rslt, n1,n2,n3,n4,n5,n6,n7,n8,n9,n10;
     

    public Ej3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_t = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        btn_cls = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(109, 109, 109));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cmb_t.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmb_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tActionPerformed(evt);
            }
        });

        jLabel1.setText("Elige el numero deseado a multiplicar");

        btn_cls.setText("Cerrar");
        btn_cls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_t, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cls, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(l5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(l10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmb_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cls))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tActionPerformed
        if (cmb_t.getSelectedIndex()==0){
                n1 = cmb_t.getSelectedIndex()+1;
                l1.setText(" " + n1 + " x 1 ="  + n1*1);
                l2.setText(" " + n1 + " x 2 ="  + n1*2);
                l3.setText(" " + n1 + " x 3 ="  + n1*3);
                l4.setText(" " + n1 + " x 4 ="  + n1*4);
                l5.setText(" " + n1 + " x 5 ="  + n1*5);
                l6.setText(" " + n1 + " x 6 ="  + n1*6);
                l7.setText(" " + n1 + " x 7 ="  + n1*7);
                l8.setText(" " + n1 + " x 8 ="  + n1*8);
                l9.setText(" " + n1 + " x 9 ="  + n1*9);
                l10.setText(" " + n1 + " x 10 ="  + n1*10);
        }
        if (cmb_t.getSelectedIndex()==1){
                n1 = cmb_t.getSelectedIndex()+1;
                l1.setText(" " + n1 + " x 1 ="  + n1*1);
                l2.setText(" " + n1 + " x 2 ="  + n1*2);
                l3.setText(" " + n1 + " x 3 ="  + n1*3);
                l4.setText(" " + n1 + " x 4 ="  + n1*4);
                l5.setText(" " + n1 + " x 5 ="  + n1*5);
                l6.setText(" " + n1 + " x 6 ="  + n1*6);
                l7.setText(" " + n1 + " x 7 ="  + n1*7);
                l8.setText(" " + n1 + " x 8 ="  + n1*8);
                l9.setText(" " + n1 + " x 9 ="  + n1*9);
                l10.setText(" " + n1 + " x 10 ="  + n1*10);
        }
        if (cmb_t.getSelectedIndex()==2){
                n1 = cmb_t.getSelectedIndex()+1;
                l1.setText(" " + n1 + " x 1 ="  + n1*1);
                l2.setText(" " + n1 + " x 2 ="  + n1*2);
                l3.setText(" " + n1 + " x 3 ="  + n1*3);
                l4.setText(" " + n1 + " x 4 ="  + n1*4);
                l5.setText(" " + n1 + " x 5 ="  + n1*5);
                l6.setText(" " + n1 + " x 6 ="  + n1*6);
                l7.setText(" " + n1 + " x 7 ="  + n1*7);
                l8.setText(" " + n1 + " x 8 ="  + n1*8);
                l9.setText(" " + n1 + " x 9 ="  + n1*9);
                l10.setText(" " + n1 + " x 10 ="  + n1*10);
        }
        if (cmb_t.getSelectedIndex()==3){
                n1 = cmb_t.getSelectedIndex()+1;
                l1.setText(" " + n1 + " x 1 ="  + n1*1);
                l2.setText(" " + n1 + " x 2 ="  + n1*2);
                l3.setText(" " + n1 + " x 3 ="  + n1*3);
                l4.setText(" " + n1 + " x 4 ="  + n1*4);
                l5.setText(" " + n1 + " x 5 ="  + n1*5);
                l6.setText(" " + n1 + " x 6 ="  + n1*6);
                l7.setText(" " + n1 + " x 7 ="  + n1*7);
                l8.setText(" " + n1 + " x 8 ="  + n1*8);
                l9.setText(" " + n1 + " x 9 ="  + n1*9);
                l10.setText(" " + n1 + " x 10 ="  + n1*10);
        }        
        if (cmb_t.getSelectedIndex()==4){
                n1 = cmb_t.getSelectedIndex()+1;
                l1.setText(" " + n1 + " x 1 ="  + n1*1);
                l2.setText(" " + n1 + " x 2 ="  + n1*2);
                l3.setText(" " + n1 + " x 3 ="  + n1*3);
                l4.setText(" " + n1 + " x 4 ="  + n1*4);
                l5.setText(" " + n1 + " x 5 ="  + n1*5);
                l6.setText(" " + n1 + " x 6 ="  + n1*6);
                l7.setText(" " + n1 + " x 7 ="  + n1*7);
                l8.setText(" " + n1 + " x 8 ="  + n1*8);
                l9.setText(" " + n1 + " x 9 ="  + n1*9);
                l10.setText(" " + n1 + " x 10 ="  + n1*10);
        }
        if (cmb_t.getSelectedIndex()==5){
                n1 = cmb_t.getSelectedIndex()+1;
                l1.setText(" " + n1 + " x 1 ="  + n1*1);
                l2.setText(" " + n1 + " x 2 ="  + n1*2);
                l3.setText(" " + n1 + " x 3 ="  + n1*3);
                l4.setText(" " + n1 + " x 4 ="  + n1*4);
                l5.setText(" " + n1 + " x 5 ="  + n1*5);
                l6.setText(" " + n1 + " x 6 ="  + n1*6);
                l7.setText(" " + n1 + " x 7 ="  + n1*7);
                l8.setText(" " + n1 + " x 8 ="  + n1*8);
                l9.setText(" " + n1 + " x 9 ="  + n1*9);
                l10.setText(" " + n1 + " x 10 ="  + n1*10);
        }
        if (cmb_t.getSelectedIndex()==6){
                n1 = cmb_t.getSelectedIndex()+1;
                l1.setText(" " + n1 + " x 1 ="  + n1*1);
                l2.setText(" " + n1 + " x 2 ="  + n1*2);
                l3.setText(" " + n1 + " x 3 ="  + n1*3);
                l4.setText(" " + n1 + " x 4 ="  + n1*4);
                l5.setText(" " + n1 + " x 5 ="  + n1*5);
                l6.setText(" " + n1 + " x 6 ="  + n1*6);
                l7.setText(" " + n1 + " x 7 ="  + n1*7);
                l8.setText(" " + n1 + " x 8 ="  + n1*8);
                l9.setText(" " + n1 + " x 9 ="  + n1*9);
                l10.setText(" " + n1 + " x 10 ="  + n1*10);
        }
        if (cmb_t.getSelectedIndex()==7){
                n1 = cmb_t.getSelectedIndex()+1;
                l1.setText(" " + n1 + " x 1 ="  + n1*1);
                l2.setText(" " + n1 + " x 2 ="  + n1*2);
                l3.setText(" " + n1 + " x 3 ="  + n1*3);
                l4.setText(" " + n1 + " x 4 ="  + n1*4);
                l5.setText(" " + n1 + " x 5 ="  + n1*5);
                l6.setText(" " + n1 + " x 6 ="  + n1*6);
                l7.setText(" " + n1 + " x 7 ="  + n1*7);
                l8.setText(" " + n1 + " x 8 ="  + n1*8);
                l9.setText(" " + n1 + " x 9 ="  + n1*9);
                l10.setText(" " + n1 + " x 10 ="  + n1*10);
        }
        if (cmb_t.getSelectedIndex()==8){
                n1 = cmb_t.getSelectedIndex()+1;
                l1.setText(" " + n1 + " x 1 ="  + n1*1);
                l2.setText(" " + n1 + " x 2 ="  + n1*2);
                l3.setText(" " + n1 + " x 3 ="  + n1*3);
                l4.setText(" " + n1 + " x 4 ="  + n1*4);
                l5.setText(" " + n1 + " x 5 ="  + n1*5);
                l6.setText(" " + n1 + " x 6 ="  + n1*6);
                l7.setText(" " + n1 + " x 7 ="  + n1*7);
                l8.setText(" " + n1 + " x 8 ="  + n1*8);
                l9.setText(" " + n1 + " x 9 ="  + n1*9);
                l10.setText(" " + n1 + " x 10 ="  + n1*10);
        }
        if (cmb_t.getSelectedIndex()==9){
                n1 = cmb_t.getSelectedIndex()+1;
                l1.setText(" " + n1 + " x 1 ="  + n1*1);
                l2.setText(" " + n1 + " x 2 ="  + n1*2);
                l3.setText(" " + n1 + " x 3 ="  + n1*3);
                l4.setText(" " + n1 + " x 4 ="  + n1*4);
                l5.setText(" " + n1 + " x 5 ="  + n1*5);
                l6.setText(" " + n1 + " x 6 ="  + n1*6);
                l7.setText(" " + n1 + " x 7 ="  + n1*7);
                l8.setText(" " + n1 + " x 8 ="  + n1*8);
                l9.setText(" " + n1 + " x 9 ="  + n1*9);
                l10.setText(" " + n1 + " x 10 ="  + n1*10);
        }
      
    }//GEN-LAST:event_cmb_tActionPerformed

    private void btn_clsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clsActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_clsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cls;
    private javax.swing.JComboBox<String> cmb_t;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
